name: Run r.py

on:
  workflow_dispatch:      # हाथ से चलाने के लिए
  push:                   # हर push पर
    paths:
      - "r.py"            # r.py बदला तो रन होगा

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install Requirements (Optional)
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run r.py
      run: |
        python3 r.py
